apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdv-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: rdv.example.com # remplace par ton domaine ou IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rdv-service
            port:
              number: 80
